name: COSP - Build CI Docker Images
run-name: CI Image Build

on: [push]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        toolchain:  [oneapi, gfortran]
        include:
        - toolchain: oneapi
          rttov_arch: ifx
        - toolchain: gfortran
          rttov_arch: gfortran
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build minimal-toolchain:${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        with:
          file: containers/Dockerfile-${{ matrix.toolchain }}-minimal
          build-args: TOOLCHAIN=${{ matrix.toolchain }}
          tags: minimal-toolchain:${{ matrix.toolchain }}

      - name: Build add-netcdf:${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        with:
          file: containers/Dockerfile-add-netcdf
          build-args: TOOLCHAIN=${{ matrix.toolchain }}
          tags: add-netcdf:${{ matrix.toolchain }}

      - name: Build add-python:${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        with:
          file: containers/Dockerfile-add-python
          build-args: TOOLCHAIN=${{ matrix.toolchain }}
          tags: add-python:${{ matrix.toolchain }}

      - name: Build add-RTTOV:${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        env: 
          rttov_tarfile_key: ${{ secrets.RTTOV_TARFILE_KEY }}
        with:
          file: containers/Dockerfile-add-RTTOV
          build-args: |
            TOOLCHAIN=${{ matrix.toolchain }}
            RTTOV_ARCH=${{ matrix.rttov_arch }}
          tags: add-rttov:${{ matrix.toolchain }}
