name: COSP Docker Images Build
run-name: Docker Image Build

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build gfortran toolchain
        uses: docker/build-push-action@v6
        with:
          file: containers/Dockerfile-gfortran
          tags: toolchain:gfortran