name: COSP ifx Docker Images Build
run-name: ifx Docker Image Build

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push rttov:${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        with:
          file: containers/Dockerfile-oneapi
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            earthsystemradiation/rttov:oneapi
            ghcr.io/earth-system-radiation/rttov:oneapi
